# Introduction to Large Language Models

TODO: introduce/explain self-attention

### Scaled Dot-Product Attention

- X is the embedding matrix
- Assume single attention layer after the embedding layer
- sequence_length=3

Input matrix:

 $$X  = 
\begin{bmatrix}
x_1   \\
x_2   \\
x_3  
\end{bmatrix}
 \in \mathbb{R}^{3 \times \textrm{embed\_dim}} $$
 
Learned attention matricies:
                    
$$ 
Q  = 
\begin{bmatrix}
q_1   \\
q_2   \\
q_3  
\end{bmatrix}
 \in \mathbb{R}^{3 \times d_q }, \ 
K  = 
\begin{bmatrix}
k_1   \\
k_2   \\
k_3  
\end{bmatrix}
 \in \mathbb{R}^{3 \times d_k }, \ 
V  = 
\begin{bmatrix}
v_1   \\
v_2   \\
v_3  
\end{bmatrix}
 \in \mathbb{R}^{3 \times d_v }\  
$$

Attention logits matrix $QK^T$:

$$ 
QK^T \in \mathbb{R}^{3 \times 3 }  = 

\begin{bmatrix}
q_1   \\
q_2   \\
q_3  
\end{bmatrix}

\cdot 

\begin{bmatrix}
k_1^T & k_2^T & k_3^T 
\end{bmatrix}

= 
 
\begin{bmatrix}
q_1 k_1^T & q_1 k_2^T & q_1 k_3^T \\
q_2 k_1^T & q_2 k_2^T & q_2 k_3^T \\
q_3 k_1^T & q_3 k_2^T & q_3 k_3^T
\end{bmatrix}

$$


Attention weight matrix $A$: 


$$ 

A \in \mathbb{R}^{3 \times 3 }  =

\begin{bmatrix}
a_{11} & a_{12} & a_{13} \\
a_{21} & a_{22} & a_{23} \\
a_{31} & a_{32} & a_{33}
\end{bmatrix} =

\textrm{Softmax} \left( \frac{Q K^T}{\sqrt{d_k}} \right) =  

\begin{bmatrix}
\frac{\exp \left( \frac{q_1 k_1^T}{\sqrt{d_k}} \right)}{\sum_{j=1}^{3} \exp \left( \frac{q_1 k_j^T}{\sqrt{d_k}} \right)} & \frac{\exp \left( \frac{q_1 k_2^T}{\sqrt{d_k}} \right)}{\sum_{j=1}^{3} \exp \left( \frac{q_1 k_j^T}{\sqrt{d_k}} \right)} & \frac{\exp \left( \frac{q_1 k_3^T}{\sqrt{d_k}} \right)}{\sum_{j=1}^{3} \exp \left( \frac{q_1 k_j^T}{\sqrt{d_k}} \right)} \\
\frac{\exp \left( \frac{q_2 k_1^T}{\sqrt{d_k}} \right)}{\sum_{j=1}^{3} \exp \left( \frac{q_2 k_j^T}{\sqrt{d_k}} \right)} & \frac{\exp \left( \frac{q_2 k_2^T}{\sqrt{d_k}} \right)}{\sum_{j=1}^{3} \exp \left( \frac{q_2 k_j^T}{\sqrt{d_k}} \right)} & \frac{\exp \left( \frac{q_2 k_3^T}{\sqrt{d_k}} \right)}{\sum_{j=1}^{3} \exp \left( \frac{q_2 k_j^T}{\sqrt{d_k}} \right)} \\
\frac{\exp \left( \frac{q_3 k_1^T}{\sqrt{d_k}} \right)}{\sum_{j=1}^{3} \exp \left( \frac{q_3 k_j^T}{\sqrt{d_k}} \right)} & \frac{\exp \left( \frac{q_3 k_2^T}{\sqrt{d_k}} \right)}{\sum_{j=1}^{3} \exp \left( \frac{q_3 k_j^T}{\sqrt{d_k}} \right)} & \frac{\exp \left( \frac{q_3 k_3^T}{\sqrt{d_k}} \right)}{\sum_{j=1}^{3} \exp \left( \frac{q_3 k_j^T}{\sqrt{d_k}} \right)}
\end{bmatrix}

$$

Note that $a_{ij}$ is the attention weight of query $q_i$ wrt key $k_j$ and indicates the level of attention that token $i$ pays on token $j$. TODO: explain why we scale by sqrt(dk) !!!

Attention output $Z$: 


$$

Z \in \mathbb{R}^{3 \times d_v } = \textrm{Softmax} \left( \frac{Q K^T}{\sqrt{d_k}} \right) \cdot V  = 

\begin{bmatrix}
a_{11} & a_{12} & a_{13} \\
a_{21} & a_{22} & a_{23} \\
a_{31} & a_{32} & a_{33}
\end{bmatrix}

\cdot 

\begin{bmatrix}
v_1   \\
v_2   \\
v_3  
\end{bmatrix}

= 
\begin{bmatrix}
a_{11}v_1 + a_{12}v_2 + a_{13}v_3 \\
a_{21}v_1 + a_{22}v_2 + a_{23}v_3 \\
a_{31}v_1 + a_{32}v_2 + a_{33}v_3
\end{bmatrix}

$$


$Z$ is the output of the attention layer, which weights the value vectors $v_i$ based on the computed attention weights. Each $z_i$ combines information from different value vectors (corresponding to different tokens) according to the attention given to each key by each query.



In [2]:
import numpy as np

# Define embedding vectors for tokens (3 tokens/sq_len, 4-dimensional embeddings)
embedding_dim = 4
X = np.array([[0.1, 0.2, 0.3, 0.4],   # Embedding for token 1
              [0.5, 0.6, 0.7, 0.8],   # Embedding for token 2
              [0.9, 1.0, 1.1, 1.2]])  # Embedding for token 3

# Define weight matrices for the transformations (W_Q, W_K, W_V)
W_Q = np.random.rand(embedding_dim, embedding_dim)  # Query weight matrix
W_K = np.random.rand(embedding_dim, embedding_dim)  # Key weight matrix
W_V = np.random.rand(embedding_dim, embedding_dim)  # Value weight matrix

# Compute the Q, K, V matrices by applying the transformations to the embeddings
Q = np.dot(X, W_Q)  # Query matrix (Q)
K = np.dot(X, W_K)  # Key matrix (K)
V = np.dot(X, W_V)  # Value matrix (V)

# Define the scaling factor (sqrt of key dimension)
d_k = K.shape[1] 
scaling_factor = np.sqrt(d_k)

# Compute the attention logits (Q K^T / sqrt(d_k))
logits = np.dot(Q, K.T) / scaling_factor

# Apply softmax to the logits to get attention weights
def softmax(x):
    return np.exp(x) / np.sum(np.exp(x), axis=1, keepdims=True)

attention_weights = softmax(logits)

# Compute the output Z (weighted sum of values)
Z = np.dot(attention_weights, V)

print("Embeddings:\n", X)
print("\nQuery Matrix (Q):\n", Q)
print("\nKey Matrix (K):\n", K)
print("\nValue Matrix (V):\n", V)
print("\nAttention Logits (Q K^T / sqrt(d_k)):\n", logits)
print("\nAttention Weights (Softmax of Logits):\n", attention_weights)
print("\nOutput Z (Weighted Sum of Values):\n", Z)

Embeddings:
 [[0.1 0.2 0.3 0.4]
 [0.5 0.6 0.7 0.8]
 [0.9 1.  1.1 1.2]]

Query Matrix (Q):
 [[0.3420103  0.62233974 0.53697047 0.29698896]
 [1.00365668 1.44684093 1.56965646 0.84233679]
 [1.66530306 2.27134213 2.60234245 1.38768462]]

Key Matrix (K):
 [[0.74303219 0.49267585 0.4881666  0.49281519]
 [1.72094183 1.15209432 1.41343988 1.28417434]
 [2.69885148 1.81151279 2.33871316 2.07553349]]

Value Matrix (V):
 [[0.73211049 0.74873158 0.5537382  0.43762437]
 [1.85844946 2.04667365 1.33752168 1.03255935]
 [2.98478842 3.34461572 2.12130517 1.62749433]]

Attention Logits (Q K^T / sqrt(d_k)):
 [[0.48461407 1.2229675  1.96132093]
 [1.31997151 3.34722716 5.37448281]
 [2.15532895 5.47148682 8.78764469]]

Attention Weights (Softmax of Logits):
 [[0.13385107 0.28008165 0.58606728]
 [0.01509429 0.11461429 0.87029142]
 [0.00126937 0.03497657 0.96375407]]

Output Z (Weighted Sum of Values):
 [[2.3677982  2.6336241  1.69196128 1.3015986 ]
 [2.8216913  3.15666997 2.00781106 1.54134604]
 [2.94253348 3.

In [4]:
# Pytorch code ???

### Masked (or causal) self-attention

In practice, transformers use a version of self-attention called masked or causal self-attention. In contrast to (bidirectional) self-attention that computes attentions scores for all tokens in the sequence, masked self-attention uses a *causal mask* that hides future tokens, so each token can attend to itself and earlier tokens. 

Example of a casual mask:

$$
\begin{array}{c|cccccc}
    & \text{The} & \text{cat} & \text{sat} & \text{on} & \text{the} & \text{mat} \\
\hline
\text{The} & 1 & 0 & 0 & 0 & 0 & 0 \\
\text{cat} & 1 & 1 & 0 & 0 & 0 & 0 \\
\text{sat} & 1 & 1 & 1 & 0 & 0 & 0 \\
\text{on}  & 1 & 1 & 1 & 1 & 0 & 0 \\
\text{the} & 1 & 1 & 1 & 1 & 1 & 0 \\
\text{mat}& 1 & 1 & 1 & 1 & 1 & 1
\end{array}
$$

Where 1 means the token can attend, 0 means it’s masked out. Note that for simplicity each word represents a token. So,
- "The" can attend only to itself.
- "cat" can attend only to "The" and "cat".
- "mat" can attend to everything in this sentence.

Usually this masking is done by setting the $q_i k_j^T$ with $i < j$ to $-\infty$ in the $QK^T$ attention logits matrix so that the application of the softmax will give zero attention weights to those positions.






In [5]:
import numpy as np

# Define embedding vectors for tokens (3 tokens/sq_len, 4-dimensional embeddings)
embedding_dim = 4
X = np.array([[0.1, 0.2, 0.3, 0.4],   # Embedding for token 1
              [0.5, 0.6, 0.7, 0.8],   # Embedding for token 2
              [0.9, 1.0, 1.1, 1.2]])  # Embedding for token 3

# Define weight matrices for the transformations (W_Q, W_K, W_V)
W_Q = np.random.rand(embedding_dim, embedding_dim)  # Query weight matrix
W_K = np.random.rand(embedding_dim, embedding_dim)  # Key weight matrix
W_V = np.random.rand(embedding_dim, embedding_dim)  # Value weight matrix

# Compute the Q, K, V matrices by applying the transformations to the embeddings
Q = np.dot(X, W_Q)  # Query matrix (Q)
K = np.dot(X, W_K)  # Key matrix (K)
V = np.dot(X, W_V)  # Value matrix (V)

# Define the scaling factor (sqrt of key dimension)
d_k = K.shape[1] 
scaling_factor = np.sqrt(d_k)

# Compute the attention logits (Q K^T / sqrt(d_k))
logits = np.dot(Q, K.T) / scaling_factor

# Create causal mask: shape (seq_len, seq_len)
seq_len = X.shape[0]
mask = np.tril(np.ones((seq_len, seq_len)))  # Lower triangular matrix including diagonal

# Apply mask: set logits where mask==0 to very large negative value (simulate -inf)
logits_masked = np.where(mask == 1, logits, -1e9)

# Apply softmax to the masked logits to get attention weights
def softmax(x):
    e_x = np.exp(x - np.max(x, axis=1, keepdims=True))  # for numerical stability
    return e_x / np.sum(e_x, axis=1, keepdims=True)

attention_weights = softmax(logits_masked)

# Compute the output Z (weighted sum of values)
Z = np.dot(attention_weights, V)

print("Embeddings:\n", X)
print("\nQuery Matrix (Q):\n", Q)
print("\nKey Matrix (K):\n", K)
print("\nValue Matrix (V):\n", V)
print("\nAttention Logits (Q K^T / sqrt(d_k)):\n", logits)
print("\nMask (1=keep, 0=mask):\n", mask)
print("\nMasked Attention Logits:\n", logits_masked)
print("\nAttention Weights (Softmax of Masked Logits):\n", attention_weights)
print("\nOutput Z (Weighted Sum of Values):\n", Z)

Embeddings:
 [[0.1 0.2 0.3 0.4]
 [0.5 0.6 0.7 0.8]
 [0.9 1.  1.1 1.2]]

Query Matrix (Q):
 [[0.37445206 0.63808738 0.53527762 0.42639362]
 [1.14268039 1.49126915 1.42375564 1.17547253]
 [1.91090873 2.34445093 2.31223366 1.92455144]]

Key Matrix (K):
 [[0.50926387 0.28276339 0.26819811 0.54880954]
 [1.13143172 0.68208795 0.66311917 1.50720176]
 [1.75359957 1.08141252 1.05804023 2.46559398]]

Value Matrix (V):
 [[0.27664098 0.61460246 0.8316572  0.46256693]
 [0.64791141 1.62860363 2.19496265 1.18161921]
 [1.01918184 2.6426048  3.55826809 1.9006715 ]]

Attention Logits (Q K^T / sqrt(d_k)):
 [[0.37434599 0.92825636 1.48216673]
 [1.01528063 2.51291775 4.01055486]
 [1.65621527 4.09757913 6.538943  ]]

Mask (1=keep, 0=mask):
 [[1. 0. 0.]
 [1. 1. 0.]
 [1. 1. 1.]]

Masked Attention Logits:
 [[ 3.74345993e-01 -1.00000000e+09 -1.00000000e+09]
 [ 1.01528063e+00  2.51291775e+00 -1.00000000e+09]
 [ 1.65621527e+00  4.09757913e+00  6.53894300e+00]]

Attention Weights (Softmax of Masked Logits):
 [[1. 

### Multi-Head Attention:

$$
\text{MultiHead}(Q, K, V) = \text{Concat}(\text{head}_1, \dots, \text{head}_h) W^O
\quad \text{where} \quad \\
\text{head}_i = \text{Attention}(Q W_i^Q, \; K W_i^K, \; V W_i^V)
$$

where the projection matrices are:
$
\quad
W_i^Q \in \mathbb{R}^{d_{\text{model}} \times d_k}, \quad
W_i^K \in \mathbb{R}^{d_{\text{model}} \times d_k}, \quad
W_i^V \in \mathbb{R}^{d_{\text{model}} \times d_v}, \quad
\text{and} \quad
W^O \in \mathbb{R}^{h d_v \times d_{\text{model}}}
$


TODO: Explain more ....



### Decoder-only transformer

Example diagram:

$$
\begin{array}{c}
\text{Input Tokens (one-hot)} \quad (T \times |V|) \\
\downarrow \\
\boxed{
\begin{array}{c}
\text{Embedding Layer}
\end{array}
} \\
\downarrow \\
\boxed{
\begin{array}{c}
\text{Positional Encoding Layer}
\end{array}
} \\
\downarrow \\
\text{Token Embeddings + Positional Encoding} \quad (T \times d_{\text{model}}) \\
\downarrow \\
\boxed{
\begin{array}{c}
\text{Decoder Block 1:} \\
\text{Masked Self-Attention} \\
\text{Feed-Forward Network} \\
\text{Layer Norm \& Residuals}
\end{array}
} \\
\downarrow \\
\boxed{
\begin{array}{c}
\text{Decoder Block 2:} \\
\text{Masked Self-Attention} \\
\text{Feed-Forward Network} \\
\text{Layer Norm \& Residuals}
\end{array}
} \\
\downarrow \\
\vdots \\
\downarrow \\
\boxed{
\begin{array}{c}
\text{Decoder Block N:} \\
\text{Masked Self-Attention} \\
\text{Feed-Forward Network} \\
\text{Layer Norm \& Residuals}
\end{array}
} \\
\downarrow \\
\text{Final hidden states} \quad (T \times d_{\text{model}}) \\
\downarrow \\
\boxed{
\begin{array}{c}
\text{Linear Layer (vocab projection)}
\end{array}
} \\
\downarrow \\
\text{Linear Layer Output} \quad (T \times |V|) \\
\downarrow \\
\boxed{
\begin{array}{c}
\text{Softmax (next token probabilities)}
\end{array}
} \\
\downarrow \\
\text{Output Probabilities} \quad (T \times |V|)
\end{array}
$$

TODO: Explain layernorm, batchnorm, residuals, positional encodings ...

TODO: Explain how is the output probabilities matrix used, e.g., for training or inference ...